### PR TITLE
Add Laravel 6.0 compatibility and fix depreciated PHPUnit methods

### PR DESCRIPTION
**Pull request by stevebauman**
This PR lays out the ground work for Laravel 6.0 compatibility, however there is currently no stable release of [Orchestra/TestBench](https://github.com/orchestral/testbench) version (4.0) for Laravel 6.0.

Once it's ready we can add it into the travis matrix and run the tests.

### CODE REVIEW

**Comment by erikgaal** [comment]
I think you can use `orchestra/testbench` either version `3.9` or `4.0` with Laravel 6, according to the release notes. A stable version of 4.0 was also [released yesterday](https://github.com/orchestral/testbench/releases/tag/v4.0.0).

**Comment by stevebauman** [comment]
@erikgaal looks like he released in 30 minutes after I created this PR. I'll update this.

**Comment by stevebauman** [comment]
We're good to go!

**Comment by Propaganistas** [comment]
Great work @stevebauman, thanks!

**Comment by Propaganistas** [comment]
New release has been created. You can update to `4.2.2`.

**Comment by stevebauman** [comment]
Awesome, thanks @Propaganistas!

**Pull request merged**
