### PR TITLE
Added Laravel 6.0 support, fixed PHPUnit depreciated methods

### PR DESCRIPTION
**Pull request by stevebauman**
I've also added the `getCountries()` public method for testing on the `PhoneNumber` class.

### CODE REVIEW

**Comment by stevebauman** [comment]
I'll also need to fix the PHPUnit methods for compatibility with 6.0 and below - if you're wanting to continue compatibility?

I think we should move to a minimum version of Laravel 5.5, as any version below no longer has support.

Thoughts?

**Comment by Propaganistas** [comment]
Thanks for your efforts. I'm at the airport right now so unable to chime in properly.

Moving to a minimum Laravel version seems the way to go. Please go ahead!

**Comment by stevebauman** [comment]
No worries! Thanks for the reply. I really appreciate your quick response, dedication and of course this package :heart:

I'll have an update shortly!

**Comment by stevebauman** [comment]
Sounds good to me! I agree completely, will have an update shortly.

**Comment by stevebauman** [comment]
Going to redo this PR - I've never re-based and updated the same PR before so bear with me!

**Pull request closed without merging**
