### PR TITLE
Add 'LENIENT' parameter for less strict validation

### PR DESCRIPTION
**Pull request by xfxf**
Hi; PR as discussed.  Tested & appears to work correctly.

### CODE REVIEW

**Comment by Propaganistas** [comment]
Thanks! Any chance to add some unit tests for this?

**Comment by Propaganistas** [comment]
Currently provided countries are not used for the lenient check.
Please update the code so a lenient check as of now is performed if no
countries were provided and otherwise use the foreach loop to perform the
lenient check using a country.

Of course please test if all is working this way...

**Comment by xfxf** [comment]
@Propaganistas acknowledged, happy to do - I somehow missed you had unit tests

**Comment by xfxf** [comment]
Hi @Propaganistas - how is this?

**Comment by Propaganistas** [comment]
Thanks for your efforts.
Could you test out the latest dev please? Tests indicate it should work, but an additional real-case check never hurts.

As soon as you report back I'll roll a new release.

**Comment by xfxf** [comment]
Hey @Propaganistas - I briefly tested this locally (and it seemed OK - that said, I'm using this in a very basic way) but this change was made for a project I'm no longer working on this year.  I've asked a coworker to test + report back here.

**Comment by splondike** [comment]
I'm the colleague xfxf was referring to. I tried out the master version of the library on our system today and it all worked fine.

**Comment by Propaganistas** [comment]
Thanks for reporting.
Tagging a new release right now.

**Pull request merged**
