### PR TITLE
Adding a PhoneNumberException interface to encapsulate all the exceptions

### PR DESCRIPTION
**Pull request by facundofarias**
The idea in here is to be able to catch all the exceptions, like this:

```
try {

# Laravel-Phone calls

} catch( PhoneNumberException $e) {
    return Redirect::back()->withErrors(['Please, review the phone number!'])->withInput();
}
```

### CODE REVIEW

**Comment by Propaganistas** [comment]
Could you elaborate on the use case? The gist of the validation logic is to silently catch all exceptions, except the ones that are caused by manual code of the developer.

**Comment by facundofarias** [comment]
Sure.
In our integration, we don't need to differentiate each one of those exceptions, but instead we need to catch all of them, so we ended up by doing this: 
```
try {
    # Laravel-Phone calls

} catch( NumberParseException | NumberFormatException | InvalidParameterException | CountryCodeException $e) {
    return Redirect::back()->withErrors(['Please, review the phone number!'])->withInput();
}
```
So, wouldn't be much easier, if we had an interface "marking" all the exception classes, and catching only that one? That was the idea. You will be able to tell me if there is some drawbacks that we didn't consider. Thanks!

**Comment by Propaganistas** [comment]
I understand your intents, but I'm having a hard time to see the bigger picture. In which contexts and/or situations are you expecting the exceptions to be thrown?

**Comment by facundofarias** [comment]
@Propaganistas Let's say a given user is trying to update their phone number. We don't care which of those exception are thrown, we just want to catch them all, and show always the same error message.

**Comment by Propaganistas** [comment]
And you're not performing any validation on that?

**Pull request closed without merging**
